/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import { deleteObjectInArray } from '@bit/aureldev.shared-reducer.object-utils/dist/objectUtils';
export { deleteObjectInArray };
import { updateObjectInArray } from '@bit/aureldev.shared-reducer.object-utils/dist/objectUtils';
export { updateObjectInArray };